spring.application.name=reactive
logging.level.root=INFO

management.endpoints.web.exposure.include=retryevents,health,info
management.endpoint.health.show-details=always

# enable retry events logging
resilience4j.retry.instances.postsRetry.event-consumer-buffer-size=50

# built-in logging via actuator - exposes /actuator/retryevents
resilience4j.retry.metrics.enabled=true

# Resilience4j retry config for postsRetry
resilience4j.retry.instances.postsRetry.max-attempts=3
resilience4j.retry.instances.postsRetry.wait-duration=500ms
resilience4j.retry.instances.postsRetry.enable-exponential-backoff=true
resilience4j.retry.instances.postsRetry.exponential-backoff-multiplier=2.0
resilience4j.retry.instances.postsRetry.exponential-max-wait-duration=5s
resilience4j.retry.instances.postsRetry.randomized-wait-factor=0.3

#resilience4j.retry.instances.postsRetry.retry-exceptions[0]=java.io.IOException
#resilience4j.retry.instances.postsRetry.retry-exceptions[1]=java.util.concurrent.TimeoutException
#resilience4j.retry.instances.postsRetry.retry-exceptions[2]=org.springframework.web.reactive.function.client.WebClientRequestException
#resilience4j.retry.instances.postsRetry.retry-exceptions[3]=org.springframework.web.reactive.function.client.WebClientResponseException
#resilience4j.retry.instances.postsRetry.ignore-exceptions[0]=java.lang.IllegalArgumentException

# Custom HTTP status properties
app.retry.status-to-retry=500,502,503,504,404