spring.application.name=reactive
logging.level.root=INFO

resilience.max-attempts=3
resilience.wait-duration=500ms
resilience.status-to-retry=404,500,503,429

resilience.retry.backoff.multiplier: 2.0
resilience.retry.backoff.jitter: 0.3
resilience.retry.backoff.max-interval: 5s